FROM python:3.13-slim

# 作業ディレクトリ
WORKDIR /home/scripts

# 必要なライブラリをまとめてインストール
RUN pip install --upgrade pip \
    && pip install psycopg2-binary meilisearch

# スクリプトをマウントする場合はコンテナ起動時にマウントする
# COPY ./scripts /home/scripts  # マウントする場合は不要